# Generated by Django 6.0.4 on 2026-04-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='annotation',
            new_name='annotations_monitor_002a10_idx',
            old_name='annotation_monitor_day_idx',
        ),
    ]
