# Generated by Django 6.0.4 on 2026-04-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monitor',
            new_name='monitors_mo_departm_9f430b_idx',
            old_name='monitors_mo_departm_4051e7_idx',
        ),
    ]
