# Generated by Django 6.0.4 on 2026-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_rename_monitors_mo_departm_4051e7_idx_monitors_mo_departm_9f430b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='department',
            field=models.CharField(choices=[('physics', 'Monitores Fisica'), ('informatics_labs', 'Monitores'), ('electrical', 'Monitores Laboratorios')], db_index=True, max_length=32),
        ),
    ]
