# Generated by Django 5.2.14 on 2026-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_alter_monitor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='department',
            field=models.CharField(choices=[('physics', 'Monitores Fisica'), ('informatics_labs', 'Monitores Aulas de Software'), ('electrical', 'Monitores Laboratorios')], db_index=True, max_length=32),
        ),
    ]
