# Generated by Django 5.2.14 on 2026-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0007_alter_monitor_proyecto_curricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='proyecto_curricular',
            field=models.CharField(blank=True, choices=[('ingenieria_electronica', 'Ingenieria electronica'), ('ingenieria_sistemas', 'Ingenieria de sistemas'), ('ingenieria_electrica', 'Ingenieria electrica'), ('ingenieria_catastral', 'Ingenieria catastral'), ('ingenieria_industrial', 'Ingenieria industrial'), ('licenciatura_fisica', 'Licenciatura en Física')], max_length=64),
        ),
    ]
