# Generated by Django 5.2.14 on 2026-08-05 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_initial_semester(apps, schema_editor):
    AcademicSemester = apps.get_model('monitors', 'AcademicSemester')
    Monitor = apps.get_model('monitors', 'Monitor')
    semester, _created = AcademicSemester.objects.get_or_create(
        name='2026-1',
        defaults={'is_active': True},
    )
    Monitor.objects.filter(semester__isnull=True).update(semester=semester)


def remove_initial_semester(apps, schema_editor):
    AcademicSemester = apps.get_model('monitors', 'AcademicSemester')
    AcademicSemester.objects.filter(name='2026-1').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0008_alter_monitor_proyecto_curricular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='codigo_estudiante',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-starts_on', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='monitors_single_active_semester')],
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitors', to='monitors.academicsemester'),
        ),
        migrations.RunPython(create_initial_semester, remove_initial_semester),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['semester', 'department', 'is_active'], name='monitors_mo_semeste_81f0fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.UniqueConstraint(fields=('semester', 'codigo_estudiante'), name='monitors_unique_code_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.UniqueConstraint(fields=('semester', 'user'), name='monitors_unique_user_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('codigo_estudiante',), name='monitors_unique_active_code'),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('user__isnull', False)), fields=('user',), name='monitors_unique_active_user'),
        ),
    ]
