# Generated by Django 5.2.17 on 2026-08-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0009_alter_monitor_codigo_estudiante_alter_monitor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='usuario_externo_id',
            field=models.UUIDField(blank=True, help_text='UUID del usuario vinculado en la plataforma de Gestión de Aulas.', null=True, unique=True),
        ),
    ]
