# Generated by Django 6.0.4 on 2026-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('physics', 'Monitores Fisica'), ('informatics_labs', 'Monitores'), ('electrical', 'Monitores Laboratorios')], db_index=True, max_length=32, null=True),
        ),
    ]
