# Generated by Django 5.2.14 on 2026-05-05 14:51

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.MonitoresUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('physics', 'Monitores Fisica'), ('informatics_labs', 'Monitores Aulas de Software'), ('electrical', 'Monitores Laboratorios')], db_index=True, max_length=32, null=True),
        ),
    ]
