# Generated by Django 5.2.17 on 2026-08-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_fix_seeded_leader_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usuario_externo_id',
            field=models.UUIDField(blank=True, help_text='UUID del usuario autenticado por la plataforma central.', null=True, unique=True),
        ),
    ]
