# Generated by Django 6.0.4 on 2026-04-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerawrecord',
            new_name='attendance__reconci_fb618c_idx',
            old_name='attendance_status_processed_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerawrecord',
            new_name='attendance__normali_1504c2_idx',
            old_name='attendance_name_department_idx',
        ),
    ]
