# Generated by Django 6.0.4 on 2026-04-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_attendance_status_processed_idx_attendance__reconci_fb618c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerawrecord',
            name='entry_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendancerawrecord',
            name='exit_at',
            field=models.TimeField(),
        ),
    ]
