# Generated by Django 6.0.4 on 2026-04-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerawrecord_worked_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerawrecord',
            name='worked_time',
        ),
    ]
