# Generated by Django 6.0.4 on 2026-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendancerawrecord_worked_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerawrecord',
            name='worked_time',
            field=models.TimeField(null=True),
        ),
    ]
