# Generated by Django 5.2.14 on 2026-05-15 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0007_alter_monitor_proyecto_curricular'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorMemorandum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('late_count_threshold', models.PositiveIntegerField()),
                ('sent_to', models.EmailField(max_length=254)),
                ('pdf_file', models.FileField(blank=True, upload_to='memorandos/%Y/%m/%d')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandums', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-late_count_threshold', '-created_at'),
                'indexes': [models.Index(fields=['monitor', 'late_count_threshold'], name='reports_mon_monitor_e7c16e_idx')],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'late_count_threshold'), name='reports_unique_monitor_memorandum_threshold')],
            },
        ),
    ]
