# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_monitormemorandum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitormemorandum",
            name="sent_to",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
