# Generated by Django 5.2.14 on 2026-08-29 01:27

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0009_alter_monitor_codigo_estudiante_alter_monitor_user_and_more'),
        ('reports', '0003_alter_monitormemorandum_sent_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentActSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_file', models.FileField(upload_to=apps.reports.models.commitment_act_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_act_submissions', to='monitors.monitor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_commitment_acts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['monitor', 'status'], name='reports_com_monitor_5f931d_idx')],
            },
        ),
    ]
