# Generated by Django 6.0.4 on 2026-04-16 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_update_schedule_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('department', models.CharField(blank=True, choices=[('physics', 'Física'), ('informatics_labs', 'Salas de Informática'), ('electrical', 'Eléctrica')], db_index=True, help_text='Déjalo vacío para que aplique a todas las dependencias.', max_length=32, null=True)),
                ('ignore_lateness', models.BooleanField(default=True, help_text='Si está activo, los retardos dentro del rango no se contabilizan.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Excepción de horario',
                'verbose_name_plural': 'Excepciones de horario',
                'ordering': ('-start_date', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='schedules_exception_end_after_start')],
            },
        ),
    ]
