# Generated by Django 5.2.14 on 2026-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_scheduleexception_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexception',
            name='department',
            field=models.CharField(blank=True, choices=[('physics', 'Monitores Fisica'), ('informatics_labs', 'Monitores Aulas de Software'), ('electrical', 'Monitores Laboratorios')], db_index=True, help_text='Déjalo vacío para que aplique a todas las dependencias.', max_length=32, null=True),
        ),
    ]
