# Generated by Django 5.2.14 on 2026-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_schedule_academic_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexception',
            name='department',
            field=models.CharField(blank=True, choices=[('physics', 'Monitores Fisica'), ('informatics_labs', 'Monitores Aulas de Software'), ('electrical', 'Monitores Laboratorios')], db_index=True, max_length=32, null=True),
        ),
    ]
