# Generated by Django 6.0.4 on 2026-04-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='worksession',
            new_name='work_sessio_monitor_83f924_idx',
            old_name='worksession_monitor_day_idx',
        ),
        migrations.RenameIndex(
            model_name='worksession',
            new_name='work_sessio_overtim_804877_idx',
            old_name='worksession_overtime_day_idx',
        ),
    ]
