# Generated by Django 6.0.4 on 2026-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0002_rename_worksession_monitor_day_idx_work_sessio_monitor_83f924_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='actual_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='actual_start',
            field=models.TimeField(),
        ),
    ]
