# Generated by Django 6.0.4 on 2026-04-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_scheduleexception'),
        ('work_sessions', '0004_worksession_normalized_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='lateness_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_sessions', to='schedules.scheduleexception'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='lateness_excused',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
